core/blog/urls.py
from django.urls import path, include
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.PostListView.as_view(), name="post-list"),
    path(
        "post/<str:slug>/", views.PostDetailView.as_view(), name="post-detail"
    ),
    path(
        "post/<str:slug>/comment/",
        views.CommentCreateView.as_view(),
        name="post-comment",
    ),
    path(
        "comment/<int:pk>/report/",
        views.CommentReportView.as_view(),
        name="report-comment",
    ),
    path("create/", views.PostCreateView.as_view(), name="post-create"),
    path(
        "post/<str:slug>/edit/",
        views.PostEditView.as_view(),
        name="post-edit",
    ),
    path(
        "post/<str:slug>/delete/",
        views.PostDeleteView.as_view(),
        name="post-delete",
    ),
    path("api/v1/", include("blog.api.v1.urls")),
]

core/templates/messages/delete_popup.html
<!-- Modal -->
<div class="modal fade" id="confirmDeleteModal" tabindex="-1" aria-labelledby="confirmDeleteLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header bg-danger text-white">
        <h5 class="modal-title" id="confirmDeleteLabel">Are you sure?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">Do you really want to delete this post?</div>
      <div class="modal-footer">
        <form id="deleteForm" method="post">
          {% csrf_token %}
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-danger">Delete</button>
        </form>
      </div>
    </div>
  </div>
</div>
<script>
  function setSlug(slug) {
    const form = document.getElementById('deleteForm')
    const baseUrl = "{% url 'blog:post-delete' 'placeholder-slug' %}"
    form.action = baseUrl.replace('placeholder-slug', slug)
  }
</script>

core/templates/messages/messages.html
{% if messages %}

  <div class="message-container" style="direction: ltr; text-align: left;">
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
  </div>
{% endif %}