core/accounts/api/v1/urls.py
from django.urls import path
from . import views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

# from rest_framework.authtoken.views import ObtainAuthToken

app_name = "api-v1"


urlpatterns = [
    path(
        "registration/",
        views.RegistrationAPIView.as_view(),
        name="registration",
    ),
    path(
        "token/login/",
        views.CustomObtainAuthToken.as_view(),
        name="token-login",
    ),
    path(
        "token/logout/", views.DiscardAuthToken.as_view(), name="token-logout"
    ),
    path(
        "jwt/create/", TokenObtainPairView.as_view(), name="token_obtain_pair"
    ),
    path("jwt/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("jwt/verify/", TokenVerifyView.as_view(), name="token_verify"),
    path(
        "change-password",
        views.ChangePasswordAPIView.as_view(),
        name="change-password",
    ),
    path("profile/", views.ProfileAPIView.as_view(), name="profile"),
    path(
        "email-verification/confirm/<str:token>/",
        views.VerifyAccountTokenAPIView.as_view(),
        name="email_verification_confirm",
    ),
    path(
        "email-verification/resend",
        views.VerificationResendAPIView.as_view(),
        name="email_verification_resend",
    ),
    path(
        "password/reset/",
        views.PasswordResetAPIView.as_view(),
        name="password_reset",
    ),
    path(
        "password/reset/confirm/<str:token>/",
        views.PasswordResetConfirmAPIView.as_view(),
        name="password_reset_confirm",
    ),
]

core/accounts/urls.py
from django.urls import path, include
from .views import (
    ProfileDetailView,
    CustomLoginView,
    SignUpView,
    VerifyAccountTokenView,
    SendVerificationEmailView,
    PasswordResetConfirmView,
    CustomPasswordChangeView,
    CustomPasswordResetView,
    CustomLogoutView,
)


app_name = "accounts"


urlpatterns = [
    path("api/v1/", include("accounts.api.v1.urls")),
    path("api/v2/", include("djoser.urls")),
    path("api/v2/", include("djoser.urls.jwt")),
    path("profile/", ProfileDetailView.as_view(), name="profile"),
    path("login/", CustomLoginView.as_view(), name="login"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:token>/", VerifyAccountTokenView.as_view(), name="verify"
    ),
    path(
        "send-verification-email/",
        SendVerificationEmailView.as_view(),
        name="send-verification-email",
    ),
    path(
        "change-password/",
        CustomPasswordChangeView.as_view(),
        name="change-password",
    ),
    path(
        "reset-password/",
        CustomPasswordResetView.as_view(),
        name="reset-password",
    ),
    path(
        "reset-password/<str:token>/",
        PasswordResetConfirmView.as_view(),
        name="reset-password-confirm",
    ),
    path("logout/", CustomLogoutView.as_view(), name="logout"),
]

core/blog/urls.py
from django.urls import path, include
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.PostListView.as_view(), name="post-list"),
    path(
        "post/<str:slug>/", views.PostDetailView.as_view(), name="post-detail"
    ),
    path(
        "post/<str:slug>/comment/",
        views.CommentCreateView.as_view(),
        name="post-comment",
    ),
    path(
        "comment/<int:pk>/report/",
        views.CommentReportView.as_view(),
        name="report-comment",
    ),
    path("create/", views.PostCreateView.as_view(), name="post-create"),
    path(
        "post/<str:slug>/edit/",
        views.PostEditView.as_view(),
        name="post-edit",
    ),
    path(
        "post/<str:slug>/delete/",
        views.PostDeleteView.as_view(),
        name="post-delete",
    ),
    path("api/v1/", include("blog.api.v1.urls")),
]

core/blog/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
import re
from decouple import config
from ckeditor_uploader.fields import RichTextUploadingField


# Create your models here.
def get_bad_words():
    return config("BAD_WORDS", default="").split(",")


URL_PATTERN = re.compile(r"(https?://\S+|www\.\S+)", re.IGNORECASE)


class Post(models.Model):
    """
    This is a class to define posts for blog app
    """

    author = models.ForeignKey(
        "accounts.Profile", on_delete=models.CASCADE, related_name="posts"
    )
    image = models.ImageField(
        upload_to="post_images/",
        blank=True,
        null=True,
        default="defaults/default_post.png",
    )
    category = models.ForeignKey(
        "Category", on_delete=models.SET_NULL, null=True
    )
    title = models.CharField(max_length=256)
    content = RichTextUploadingField()
    status = models.BooleanField()
    slug = models.SlugField(unique=True, blank=True)

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField()

    def save(self, *args, **kwargs):
        if not self.slug:
            base_slug = slugify(self.title)
            slug = base_slug
            counter = 1
            while Post.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            self.slug = slug
        super().save(*args, **kwargs)

    def get_snippet(self):
        words = self.content.split()
        snippet = " ".join(words[:10])
        return snippet + "..." if len(words) > 10 else snippet

    def get_absolute_url(self):
        return reverse("blog:api-v1:post-detail", kwargs={"slug": self.slug})

    def __str__(self):
        return self.title


class Category(models.Model):

    name = models.CharField(max_length=50, unique=True)

    def get_absolute_url(self):
        return reverse(
            "blog:api-v1:category-detail", kwargs={"name": self.name}
        )

    def __str__(self):
        return self.name


class Comment(models.Model):
    author = models.ForeignKey("accounts.Profile", on_delete=models.CASCADE)
    post = models.ForeignKey("Post", on_delete=models.CASCADE)
    text = models.TextField()
    parent = models.ForeignKey(
        "self",
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name="replies",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    is_approved = models.BooleanField(default=False)
    is_hidden = models.BooleanField(default=False)
    report_count = models.PositiveIntegerField(default=0)
    is_flagged_by_system = models.BooleanField(default=False)

    def flag_if_inappropriate(self):
        inappropriate_keywords = get_bad_words()
        text_lower = self.text.lower()
        if any(
            keyword in text_lower for keyword in inappropriate_keywords
        ) or URL_PATTERN.search(text_lower):
            self.is_flagged_by_system = True
            self.is_hidden = True

    def report(self):
        self.report_count += 1
        self.author.decrease_score(5)
        if self.report_count >= 5:
            self.is_hidden = True
        self.save()

    def __str__(self):
        return f"{self.author} - {self.text[:10]}"


class CommentReport(models.Model):
    user = models.ForeignKey("accounts.Profile", on_delete=models.CASCADE)
    comment = models.ForeignKey("Comment", on_delete=models.CASCADE)
    reported_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("user", "comment")

    def __str__(self):
        return f"{self.user} -> {self.comment}"

core/accounts/api/v1/views.py
from rest_framework.generics import GenericAPIView, RetrieveUpdateAPIView
from rest_framework import status
from rest_framework.response import Response
from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework.authtoken.models import Token
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated, AllowAny
from rest_framework_simplejwt.tokens import AccessToken
from rest_framework_simplejwt.exceptions import TokenError
from django.shortcuts import get_object_or_404
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from rest_framework.parsers import MultiPartParser, FormParser

from ...utils import (
    APIChangePasswordThrottle,
    APIResetPasswordThrottle,
    APIRegisterThrottle,
    APIVerificationResendThrottle,
)
from ...models import Profile
from .serializers import (
    RegistrationSerializer,
    CustomAuthTokenSerializer,
    ChangePasswordSerializer,
    ProfileSerializer,
    PasswordResetConfirmSerializer,
)
from ...tasks import send_verification_email, send_password_reset_email


User = get_user_model()


class RegistrationAPIView(GenericAPIView):
    """
    API endpoint for user registration.

    - Accepts: email, password, password1
    - Validates password strength and sends verification email asynchronously.
    - Returns: 201 Created with email on success
    - Only accessible to unauthenticated users.
    """

    serializer_class = RegistrationSerializer
    permission_classes = [AllowAny]
    throttle_classes = [APIRegisterThrottle]

    def post(self, request, *args, **kwargs):
        throttle = self.get_throttles()[0]
        throttle.record_attempt(request)

        serializer = self.get_serializer(data=request.data)

        if not serializer.is_valid():
            return Response(
                serializer.errors, status=status.HTTP_400_BAD_REQUEST
            )

        serializer.save()
        email = serializer.validated_data["email"]
        user = User.objects.get(email=email)

        # Send verification email asynchronously
        send_verification_email.delay(user.id)
        throttle.reset_level(request)
        return Response({"email": email}, status=status.HTTP_201_CREATED)


class CustomObtainAuthToken(ObtainAuthToken):
    """
    API endpoint for obtaining an authentication token using email and password.

    - Accepts email/password
    - Returns token, user ID, and email
    - Compatible with TokenAuthentication
    """

    permission_classes = [AllowAny]
    serializer_class = CustomAuthTokenSerializer

    def post(self, request, *args, **kwargs):
        """
        Handle POST request to authenticate user and return auth token.
        """
        serializer = self.serializer_class(
            data=request.data, context={"request": request}
        )
        serializer.is_valid(raise_exception=True)

        user = serializer.validated_data["user"]
        token, _ = Token.objects.get_or_create(user=user)

        return Response(
            {"token": token.key, "user_id": user.pk, "email": user.email}
        )


class DiscardAuthToken(APIView):
    """
    API endpoint to manually invalidate (delete) a user's authentication token.

    - Requires the user to be authenticated.
    - Deletes the associated token to log the user out from token-based sessions.
    - Returns HTTP 200 on success.
    """

    permission_classes = [IsAuthenticated]

    def post(self, request, format=None):
        """
        Handle POST request to discard the current user's authentication token.
        """
        # Delete the user's current token (token-based logout)
        request.user.auth_token.delete()

        # Respond with success status
        return Response(
            {"detail": _("Token discarded successfully.")},
            status=status.HTTP_200_OK,
        )


class ChangePasswordAPIView(GenericAPIView):
    """
    API endpoint for allowing authenticated users to change their password.

    Features:
    - Requires authentication (IsAuthenticated)
    - Applies custom throttle to limit password change frequency
    - Validates current password, confirmation, and strength
    - Uses Django's password validation system for security enforcement
    """

    serializer_class = ChangePasswordSerializer
    permission_classes = [IsAuthenticated]
    throttle_classes = [APIChangePasswordThrottle]

    def put(self, request, *args, **kwargs):
        throttle = self.get_throttles()[0]
        throttle.record_attempt(request)
        user = request.user

        # Initialize serializer with request data and user context
        serializer = self.get_serializer(
            data=request.data, context={"user": user}
        )

        if not serializer.is_valid():
            # Return validation errors if input is invalid
            return Response(
                serializer.errors, status=status.HTTP_400_BAD_REQUEST
            )

        # Set the new validated password and save the user
        user.set_password(serializer.validated_data["new_password"])
        user.save()
        throttle.reset_level(request)
        # Return success response upon password change
        return Response(
            {"success": _("Password updated successfully.")},
            status=status.HTTP_200_OK,
        )


class ProfileAPIView(RetrieveUpdateAPIView):
    """
    API endpoint that allows authenticated users to retrieve and update their profile.

    - GET:    Retrieve the current user's profile data.
    - PUT:    Fully update the user's profile.
    - PATCH:  Partially update the user's profile.
    """

    serializer_class = ProfileSerializer
    permission_classes = [IsAuthenticated]
    parser_classes = [MultiPartParser, FormParser]

    def get_object(self):
        """
        Returns the profile instance of the currently authenticated user.
        """
        return get_object_or_404(Profile, user=self.request.user)

    def perform_update(self, serializer):
        """
        Hook for performing custom actions when saving the updated profile.
        """
        serializer.save()

    def update(self, request, *args, **kwargs):
        """
        Handles PUT and PATCH requests to update the authenticated user's profile.

        Returns a custom success message and the updated profile data upon success.
        """
        partial = kwargs.pop("partial", False)
        instance = self.get_object()
        serializer = self.get_serializer(
            instance, data=request.data, partial=partial
        )

        if serializer.is_valid():
            serializer.save()
            return Response(
                {
                    "message": _("Profile updated successfully."),
                    "data": serializer.data,
                },
                status=status.HTTP_200_OK,
            )
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class VerifyAccountTokenAPIView(APIView):
    """
    API view to verify user's account via token.
    """

    permission_classes = [AllowAny]

    def get(self, request, token, *args, **kwargs):
        try:
            # Decode the token
            access_token = AccessToken(token)

            # Ensure token purpose is email verification
            if access_token.get("purpose") != "email_verification":
                return Response(
                    {"detail": _("Invalid token purpose.")},
                    status=status.HTTP_400_BAD_REQUEST,
                )

            # Get user from token payload
            user_id = access_token["user_id"]
            user = User.objects.get(id=user_id)

        except TokenError:
            return Response(
                {"detail": _("Invalid or expired activation link.")},
                status=status.HTTP_400_BAD_REQUEST,
            )
        except User.DoesNotExist:
            return Response(
                {"detail": _("User does not exist.")},
                status=status.HTTP_400_BAD_REQUEST,
            )

        # If user is already verified
        if user.is_verified:
            return Response(
                {"detail": _("Your account is already verified.")},
                status=status.HTTP_200_OK,
            )

        # Verify the user
        user.is_verified = True
        user.save()

        return Response(
            {"detail": _("Your account has been successfully verified.")},
            status=status.HTTP_200_OK,
        )


class VerificationResendAPIView(APIView):
    """
    Resend verification email with a custom 5-minute cooldown per user.
    Uses both custom cooldown and DRF global throttling.
    """

    permission_classes = [IsAuthenticated]
    throttle_classes = [APIVerificationResendThrottle]

    def post(self, request, *args, **kwargs):
        throttle = self.get_throttles()[0]
        throttle.record_attempt(request)
        user = request.user

        if user.is_verified:
            return Response(
                {"detail": _("Your account is already verified.")},
                status=status.HTTP_400_BAD_REQUEST,
            )

        send_verification_email.delay(user.id)
        throttle.reset_level(request)
        return Response(
            {"detail": _("Verification email sent successfully.")},
            status=status.HTTP_200_OK,
        )


class PasswordResetAPIView(APIView):
    """
    API view to request a password reset. Accepts an email and triggers an async email task.
    """

    permission_classes = [AllowAny]
    throttle_classes = [APIResetPasswordThrottle]

    def post(self, request):
        throttle = self.get_throttles()[0]
        throttle.record_attempt(request)

        email = request.data.get("email")
        if not email:
            return Response(
                {"detail": "Email field is required."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        try:

core/templates/accounts/password_change.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'accounts/ChangePassword.css' %}" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" />
    <title>Change Password</title>
  </head>
  <body>
    {% include "messages/messages.html" %}
    <div class="change-password-container">
      <h2>Change Password</h2>

      <form method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}

        <div class="form-group">
          <label for="{{ form.old_password.id_for_label }}">Current Password:</label>
          {{ form.old_password }}
          <i class="bi bi-eye-slash toggle-password" onclick="togglePassword('id_old_password', this)"></i>
          {{ form.old_password.errors }}
        </div>

        <div class="form-group">
          <label for="{{ form.new_password1.id_for_label }}">New Password:</label>
          {{ form.new_password1 }}
          <i class="bi bi-eye-slash toggle-password" onclick="togglePassword('id_new_password1', this)"></i>
          {{ form.new_password1.errors }}
        </div>

        <div class="form-group">
          <label for="{{ form.new_password2.id_for_label }}">Confirm New Password:</label>
          {{ form.new_password2 }}
          <i class="bi bi-eye-slash toggle-password" onclick="togglePassword('id_new_password2', this)"></i>
          {{ form.new_password2.errors }}
        </div>

        <button class="btn btn-primary" type="submit">Submit</button>
      </form>
    </div>

    <script src="{% static 'accounts/ChangePassword.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

core/templates/accounts/password_reset.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'accounts/signIN.css' %}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" />
    <title>Reset Password</title>
  </head>
  <body>
    {% include 'messages/messages.html' %}

    <div class="signin-form">
      <h2>Reset Password</h2>
      <form method="post" action="{% url 'accounts:reset-password' %}">
        {% csrf_token %}
        {{ form.non_field_errors }}

        <div>{{ form.email.errors }}
          {{ form.email }}</div>

        <button type="submit" class="btn">Send</button>
      </form>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

core/templates/accounts/password_reset_confirm.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'accounts/ChangePassword.css' %}" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" />
    <title>Reset Password</title>
  </head>
  <body>
    {% include "messages/messages.html" %}
    <div class="change-password-container">
      <h2>Reset Password</h2>

      <form method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}

        <div class="form-group">
          <label for="{{ form.new_password1.id_for_label }}">New Password:</label>
          {{ form.new_password1 }}
          <i class="bi bi-eye-slash toggle-password" onclick="togglePassword('id_new_password1', this)"></i>
          {{ form.new_password1.errors }}
        </div>

        <div class="form-group">
          <label for="{{ form.new_password2.id_for_label }}">Confirm New Password:</label>
          {{ form.new_password2 }}
          <i class="bi bi-eye-slash toggle-password" onclick="togglePassword('id_new_password2', this)"></i>
          {{ form.new_password2.errors }}
        </div>

        <button class="btn btn-primary" type="submit">Submit</button>
      </form>
    </div>

    <script src="{% static 'accounts/ChangePassword.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

core/templates/accounts/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'accounts/profile.css' %}" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" />
    <title>User Profile</title>
  </head>
  <body>
    {% include 'messages/messages.html' %}
    {% include 'messages/delete_popup.html' %}

    <!-- Back to Posts Button -->
    <div class="back-to-posts-card" style="margin: 20px;">
      <a href="{% url 'blog:post-list' %}" class="btn btn-secondary">Home</a>
    </div>


    <div class="profile-container">

      <div class="text-center my-3">
        <button class="btn btn-primary" onclick="toggleEditForm()">Edit Profile</button>
      </div>

      <!-- Edit Form -->
      <div id="editForm" style="display: none;">
        <form method="POST" enctype="multipart/form-data" class="p-4 border rounded bg-white shadow-sm">
          {% csrf_token %}

          <!-- Profile Image -->
          <div class="mb-4 text-center">
            <img src="{{ profile.image.url }}" class="rounded-circle" width="100" height="100" alt="Profile" />
          </div>

          <!-- First Name Field -->
          <div class="mb-3">
            <label for="{{ form.first_name.id_for_label }}" class="form-label">First Name</label>
            <input type="text" name="{{ form.first_name.name }}" value="{{ form.first_name.value }}" class="form-control" id="{{ form.first_name.id_for_label }}" />
          </div>

          <!-- Last Name Field -->
          <div class="mb-3">
            <label for="{{ form.last_name.id_for_label }}" class="form-label">Last Name</label>
            <input type="text" name="{{ form.last_name.name }}" value="{{ form.last_name.value }}" class="form-control" id="{{ form.last_name.id_for_label }}" />
          </div>

          <!-- Description Field -->
          <div class="mb-3">
            <label for="{{ form.description.id_for_label }}" class="form-label">Description</label>
            <textarea name="{{ form.description.name }}" class="form-control" id="{{ form.description.id_for_label }}">{{ form.description.value }}</textarea>
          </div>

          <!-- Image Field -->
          <div class="mb-3">
            <label for="{{ form.image.id_for_label }}" class="form-label">Profile Image</label>
            <input type="file" name="{{ form.image.name }}" class="form-control" id="{{ form.image.id_for_label }}" />
          </div>

          <button type="submit" class="btn btn-success">Save Changes</button>
        </form>
      </div>

      <!-- Email Information -->
      <div class="mt-4">
        <label>Email:</label>
        <span>{{ profile.email }}</span>
        {% if profile.user.is_verified %}
          <span class="badge bg-success">Verified</span>
        {% else %}
          <a href="{% url 'accounts:send-verification-email' %}" class="badge bg-danger">Verify Email</a>
        {% endif %}
      </div>

      <!-- Change Password Button -->
      <div class="mt-3">
        <a href="{% url 'accounts:change-password' %}" class="btn btn-warning">Change Password</a>
      </div>
      <hr />
      {% if perms.blog.add_post %}
        <div class="posts">
          <h3>Created Posts:</h3>

          <a href="{% url 'blog:post-create' %}" class="addPost-btn">Add New Post +</a>

          {% if profile.posts.all %}
            <ul id="userPostsList" class="user-posts">
              {% for post in profile.posts.all %}
                <li>
                  <a href="{% url 'blog:post-detail' slug=post.slug %}">{{ forloop.counter }}. {{ post.title }}</a>
                  <div class="icons">
                    <a href="{% url 'blog:post-edit' slug=post.slug %}"><i class="bi bi-pencil-square" title="Edit"></i></a>
                    <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal" onclick="setSlug('{{ post.slug }}')"><i class="bi bi-trash"></i></button>
                  </div>
                </li>
              {% endfor %}
            </ul>
          {% else %}
            <p>You haven't created any posts yet.</p>
          {% endif %}
        </div>
      {% endif %}
    </div>
    <!-- Script to toggle the edit form -->
    <script>
      function toggleEditForm() {
        var form = document.getElementById('editForm')
        form.style.display = form.style.display === 'none' ? 'block' : 'none'
      }
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

core/templates/accounts/signin.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'accounts/signIN.css' %}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" />
    <title>Login</title>
  </head>
  <body>
    {% include 'messages/messages.html' %}

    <div class="signin-form">
      <h2>Login</h2>
      <form method="post" action="{% url 'accounts:login' %}">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {% if request.GET.next %}
          <input type="hidden" name="next" value="{{ request.GET.next }}" />
        {% endif %}
        <div>{{ form.username.errors }}
          {{ form.username }}</div>
        <div>{{ form.password.errors }}
          {{ form.password }}</div>

        <button type="submit" class="btn">Login</button>
        <a class="backTO-signUP" href="{% url 'accounts:signup' %}">Don't have an account?</a>
        <a class="backTO-signUP" href="{% url 'accounts:reset-password' %}">Forgot your password?</a>
      </form>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

core/templates/accounts/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'accounts/signUP.css' %}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" />
    <title>Sign Up</title>
  </head>
  <body>
    {% include 'messages/messages.html' %}

    <div class="signup-form">
      <h2>Sign Up</h2>
      <form method="post" action="{% url 'accounts:signup' %}">
        {% csrf_token %}
        {{ form.non_field_errors }}

        <div>{{ form.email.errors }}
          {{ form.email }}</div>

        <div>{{ form.password1.errors }}
          {{ form.password1 }}</div>

        <div>{{ form.password2.errors }}
          {{ form.password2 }}</div>

        <button type="submit" class="btn">Sign Up</button>
        <a class="backTo-signIN" href="{% url 'accounts:login' %}">Already have an account?</a>
      </form>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>